### ISSUE TITLE
Saknad information

### ISSUE THREAD

**Issue by AndersNilsson19** [niklasmelin/nibepi-homeassistant#2]
Du får gärna lägga till i denna text att det är "nummer" helper man skall välja i menyn. 
https://github.com/niklasmelin/nibepi-homeassistant/blob/main/configs/status_image_with_temperature_control/status_image_with_temperature_control.md 
Mvh!
![Skärmbild 2024-03-23 163910](https://github.com/niklasmelin/nibepi-homeassistant/assets/141344261/84f49e40-c5ca-40c6-bcfb-c8be7e18c012)

**Comment by niklasmelin** [comment]
This has been updated in the next release with more descriptive text.
